function CT04_panel_straj_estimation(h,panel_straj_estimation)
%CT02_PANEL_SUPERTRAJS Summary of this function goes here
%   Detailed explanation goes here
    

    uicontrol('style','listbox','Parent',panel_straj_estimation,        ...
                                         'String','' ,                 ...
                                         'Units','normalized',         ... 
                                          'Position',[0.1 0.1 0.75 0.8], ...
                                         'Callback',{@listbox_processingCallback,h}, ...
                                          'FontSize',12, ...
                                          'FontWeight','bold', ...
                                         'Tag','listbox');



    h.javacomponets.signal_layer.add_supertraj_btn    = add_btn('Parent',panel_straj_estimation, ...
                                                            'Position',[0.85 0.6 0.15 0.15], ...
                                                            'Callback',{@add_processingCallback,h}, ...
                                                            'Tag','add');
    
    
    h.javacomponets.signal_layer.minus_supertraj_btn  = minus_btn('Parent',panel_straj_estimation, ...
                                                            'Position',[0.85 0.3 0.15 0.15], ...
                                                            'Callback',{@minus_processingCallback,h}, ...
                                                         'Tag','minus');
end

