function CT04_panel_control(h,panel_control)
%CT04_PANEL_CONTROL Summary of this function goes here
%   Detailed explanation goes here

    %% Tabs 
    tabgp = uitabgroup(panel_control,                       ...
                       'Units','normalize',                 ...
                       'Position',[0.00 0.00 0.65 1],       ...
                       'Tag','Tab');          


           color = [ 0 0 0.75];

            % Deafult Methods 
           tab_default_methods   = uitab(tabgp,'Title','Default Methods','Tag','Default Methods');
           tab_default_methods.ForegroundColor = color;

            x = 0.025;y =0.65; w = 0.15; hight= 0.15;
            %
            textpop = uicontrol('style','text','Parent',tab_default_methods,  ...
                                               'String','Methods',            ...
                                               'Units','normalized',          ...
                                               'Position',[x y w hight+0.125]);

            %
            popup = uicontrol('style','popupmenu',                          ...
                      'String',{'EKF','UKF','Filter Particles'},    ...
                      'Parent',tab_default_methods,                       ...
                      'Units','normalized',                         ...
                      'Position',[x-0.020 y-0.25 w+0.06 hight],                ...
                      'Tag','popupmenu');


            %% Paremeters Model
            panel_parameter_methods =uipanel(tab_default_methods,'Title','Parameters Methods','Tag','Parameters Methods','Units','normalized','Position',[0.225 0.05 0.775 0.95]);
            
            CT04_parameter_methods(h,panel_parameter_methods)
            

            % User Methods
            tab_user_methods   = uitab(tabgp,'Title','User Methods','Tag','User Methods');
            tab_user_methods.ForegroundColor = color;
    
  %% Initial State
        panel_other = uipanel(panel_control,'Units','normalized','Position',[0.65 0.05 0.25 0.95],'Title','Initial State','Tag','Initial State');
        
                uicontrol('style','checkbox','Parent',panel_other,'String','By default','Units','normalized','Position',[0.1 0.7 0.8 0.3],'Tag','By default','Callback',{@checkbox_bydefault,h})
                uicontrol('style','text','Parent',panel_other,'String','[  x  ,   y  ,   h  ,  vx  , vy  ]','Units','normalized','Position',[0.0 0.475 1 0.25],'FontSize',15)
                uicontrol('style','edit','Parent',panel_other,'String','[0.00 , 0.00 , 0.00 , 0.00 , 0.00]','Units','normalized','Position',[0.05 0.15 0.9 0.3],'Tag','InitialState')

  %% Compute!
        uicontrol('Style','pushbutton',             ...
                  'Parent',panel_control,           ...
                  'Units','normalized',             ...
                  'Position',[0.915 0.5 0.075 0.3],   ...
                  'String','Compute!',              ...
                  'Callback',{@btnComputeCallback,h});
              
    %% Animation
        uicontrol('Style','pushbutton',             ...
                  'Parent',panel_control,           ...
                  'Units','normalized',             ...
                  'Position',[0.915 0.2 0.075 0.3],   ...
                  'String','Animation',             ...
                  'Tag','Animation',                ...
                  'Callback',{@animationProcessingCallback,h});            
end

