function CT04_parameter_methods(h,panel_parameter_methods)
%CT04_PARAMETER_METHODS Summary of this function goes here
%   Detailed explanation goes here
    
        %% Process Noise
        uicontrol('style','text','Parent',panel_parameter_methods,  ...
                                 'String',{'Process','Noise'},          ...
                                 'Units','normalized',              ...
                                 'Position',[0.025 0.1 0.15 0.7]);

        uicontrol('style','edit','Parent',panel_parameter_methods,  ...
                                 'String','[1.0 1.0 1.0 1.0]',      ...
                                 'Units','normalized',              ...
                                 'Position',[0.2 0.15 0.275 0.5],    ...
                                 'Tag','Process Noise')
        %%   Signal Noise     
        uicontrol('style','text','Parent',panel_parameter_methods,  ...
                                 'String',{'Signal','Noise'},          ...
                                 'Units','normalized',              ...
                                 'Position',[0.5 0.1 0.15 0.7]);
                             
        uicontrol('style','popupmenu','Parent',panel_parameter_methods, ...
                                      'String',{'RSS','ToF','AoA','Baro','Magne'}, ...
                                      'Units','normalized',                          ...
                                      'Position',[0.65 0.4 0.20 0.25])
        %% edit                          
        uicontrol('style','edit','Parent',panel_parameter_methods, ...
                                 'Units','normalized',              ...
                                 'Position',[0.875 0.225 0.10 0.4])
end

