function CT01_pc_dimension(h,panel_dimension)

    %%
    text_xlim = uicontrol('style','text','Parent',panel_dimension, ...
                                           'String','xlim(m)',     ...
                                           'Units','normalized',  ...
                                           'Position',[0.05 0.5 0.15 0.3]);
    edit_xlim = uicontrol('style','edit','Parent',panel_dimension, ...
                                           'String','50',          ...
                                           'Units','normalized',  ...
                                           'Position',[0.25 0.5 0.1 0.3], ...
                                           'Tag','xlim');
    %%
    text_ylim = uicontrol('style','text','Parent',panel_dimension, ...
                                           'String','ylim(m)',     ...
                                           'Units','normalized',  ...
                                           'Position',[0.05 0.05 0.15 0.3]);
    edit_ylim = uicontrol('style','edit','Parent',panel_dimension, ...
                                           'String','50',          ...
                                           'Units','normalized',  ...
                                           'Position',[0.25 0.1 0.1 0.3], ...
                                           'Tag','ylim');
    %%
   btn_fix = uicontrol('style','pushbutton','Parent',panel_dimension, ...
                                           'String','fix',          ...
                                           'Units','normalized',  ...
                                           'Position',[0.375 0.3 0.1 0.3], ...
                                           'Callback',{@btn_fix_planimetry,h}, ...
                                           'Tag','btnfix');
                                       
                                       
    %%                                   
    text_xlim_scale = uicontrol('style','text','Parent',panel_dimension, ...
                                           'String','xlim(scale)',     ...
                                           'Units','normalized',  ...
                                           'Position',[0.55 0.5 0.2 0.3]);
    edit_xlim_scale = uicontrol('style','edit','Parent',panel_dimension, ...
                                           'String','1',          ...
                                           'Units','normalized',  ...
                                           'Position',[0.75 0.5 0.1 0.3], ...
                                           'Tag','xlimscale');
    %%
    text_ylim_scale = uicontrol('style','text','Parent',panel_dimension, ...
                                           'String','ylim(scale)',     ...
                                           'Units','normalized',  ...
                                           'Position',[0.55 0.05 0.2 0.3]);
    edit_ylim_scale = uicontrol('style','edit','Parent',panel_dimension, ...
                                           'String','1',          ...
                                           'Units','normalized',  ...
                                           'Position',[0.75 0.1 0.1 0.3], ...
                                           'Tag','ylimscale');                                       
    %%                                   
    btn_scale = uicontrol('style','pushbutton','Parent',panel_dimension, ...
                                           'String','Scale',          ...
                                           'Units','normalized',  ...
                                           'Position',[0.875 0.3 0.1 0.3], ...
                                           'Callback',{@btn_scale_planimetry,h}, ...
                                           'Tag','btnscale');    
end

