function CT01_pc_png(h,panel_png)

    %% Buttons 
    main_panel = uipanel('Parent',panel_png,'Unit','norm','Position',[0.0 0.0 0.7 1.0]);
    
    %% PNG path
    edit_label          = uicontrol('style','edit','String',' ','Parent',main_panel,'Tag','path');
    edit_label.Enable = 'off';
    edit_label.Units       = 'normalized';
    edit_label.Position    = [0.025 0.25 0.45 0.5];
    
    firstx = 0.49;
    wbtn = 0.11;
    ybtn = 0.325;
    interspace = 0.02;
    btn_load_png = uicontrol('style','pushbutton','String','load',                  ...
                                                  'Parent',main_panel,               ...
                                                  'Units','normalized',             ...
                                                  'Position',[firstx ybtn wbtn 0.35],    ...
                                                   'Enable','off',            ...
                                                  'Callback',{@btn_loadCallback,h}, ...
                                                  'Tag','btnload');
                                              
    btn_edit = uicontrol('style','pushbutton','String','edit',                  ...
                                                  'Parent',main_panel,               ...
                                                  'Units','normalized',             ...
                                                   'Enable','off',            ...
                                                  'Position',[firstx + wbtn + interspace ybtn wbtn 0.35],    ...
                                                  'Callback',{@btn_editpngCallback,h}, ...
                                                  'Tag','btnedit');
                                              
    btn_remove_png = uicontrol('style','pushbutton','String','remove',                  ...
                                                  'Parent',main_panel,               ...
                                                  'Units','normalized',             ...
                                                   'Enable','off',            ...
                                                  'Position',[firstx + 2*wbtn + 2*interspace ybtn wbtn 0.35],    ...
                                                  'Callback',{@btn_removeCallback,h}, ...
                                                  'Tag','btnremove');
    
     btn_ok_png = uicontrol('style','pushbutton','String','Ok',                  ...
                                                  'Parent',main_panel,               ...
                                                  'Units','normalized',             ...
                                                   'Enable','off',            ...
                                                  'Position',[firstx + 3*wbtn + 3*interspace ybtn wbtn 0.35],    ...
                                                  'Callback',{@btn_okpngCallback,h}, ...
                                                  'Tag','btnok');                                             
    %%
   sec_panel = uipanel('Parent',panel_png,'Unit','norm','Position',[0.7 0.0 0.3 1.0]);

%     checkbox_view =  uicontrol('style','checkbox','String',{'View'},                      ...
%                                                   'Parent',sec_panel,                   ...
%                                                   'Units','normalized',                 ...
%                                                   'Enable','off',            ...
%                                                   'Position',[0.65 0.1 0.15 0.5],       ...    
%                                                   'Callback',{@check_viewCallback,h},   ...
%                                                   'Tag','checkboxview');
   
                                              
    uicontrol('style','text','String','Angle','Parent',sec_panel,'Unit','norm','Position',[0.1 0.7 0.8 0.2]);
    btn_move_png = uicontrol('style','slider','Parent',sec_panel,'Unit','norm','Position',[0.1 0.4 0.8 0.2],'Callback',{@slider_callback_angle,h},'Min',0,'Max',360,'Tag','Angle','Enable','off');  
    
    %%
    uicontrol('style','text','String','0º','Parent',sec_panel,'Unit','norm','Position',[0.075 0.15 0.1 0.2]);
    uicontrol('style','text','String','360º','Parent',sec_panel,'Unit','norm','Position',[0.775 0.15 0.2 0.2]);

end

