function CT01_pc_png(h,panel_png)

    %% PNG path
    edit_label          = uicontrol('style','edit','String',' ','Parent',panel_png,'Tag','path');
    edit_label.Units       = 'normalized';
    edit_label.Position    = [0.05 0.25 0.55 0.5];
    
    %% Buttons 
    btn_load_png = uicontrol('style','pushbutton','String','load',                  ...
                                                  'Parent',panel_png,               ...
                                                  'Units','normalized',             ...
                                                  'Position',[0.65 0.55 0.15 0.35],    ...
                                                  'Callback',{@btn_loadCallback,h}, ...
                                                  'Tag','btnload');
                                              
    btn_remove_png = uicontrol('style','pushbutton','String','remove',                  ...
                                                  'Parent',panel_png,               ...
                                                  'Units','normalized',             ...
                                                  'Position',[0.65 0.15 0.15 0.35],    ...
                                                  'Callback',{@btn_removeCallback,h}, ...
                                                  'Tag','btnremove');
    
    checkbox_view =  uicontrol('style','checkbox','String',{'View'},                      ...
                                                  'Parent',panel_png,                   ...
                                                  'Units','normalized',                 ...
                                                  'Position',[0.845 0.1 0.2 0.5],       ...    
                                                  'Callback',{@check_viewCallback,h},   ...
                                                  'Tag','checkboxview');

    btn_move_png = uicontrol('style','togglebutton','String','move',                  ...
                                                  'Parent',panel_png,               ...
                                                  'Units','normalized',             ...
                                                  'Position',[0.825 0.55 0.15 0.35],    ...
                                                  'Callback',{@btn_movePNGCallback,h}, ...
                                                  'Tag','btnmove');    
                                              
end

