function CT01_pc_levels(h,panel_levels)
%% Panel Title: Levels


    listbox_levels     = uicontrol('style','listbox',    'Parent',panel_levels,    ...
                                                         'String','0',             ...
                                                         'Units','normalized',     ... 
                                                         'Position',[0.05 0.1 0.155 0.8], ...
                                                         'Callback',{@listbox_planimetryCallback,h}, ...
                                                         'Tag','listbox');
    
    button_add_level   = uicontrol('style','pushbutton','Parent',panel_levels, ...
                                                        'FontSize',15,         ...
                                                        'String','+',          ...
                                                        'Units','normalized',  ...
                                                        'Position',[0.25 0.5 0.08 0.3], ...
                                                        'Callback',{@btn_addCallback,h}, ...
                                                        'Tag','add');
                                                    
    button_minus_level = uicontrol('style','pushbutton','Parent',panel_levels, ...
                                                        'FontSize',15,         ...
                                                        'String','-',          ...
                                                        'Units','normalized',  ...
                                                        'Position',[0.25 0.2 0.08 0.3], ...
                                                        'Callback',{@btn_minusCallback,h}, ...
                                                        'Tag','minus');

                                                    
    text_hieght = uicontrol('style','text','Parent',panel_levels, ...
                                           'String','Height',     ...
                                           'Units','normalized',  ...
                                           'Position',[0.45 0.55 0.15 0.3]);
                                       
    edit_hieght = uicontrol('style','edit','Parent',panel_levels,              ...
                                           'String','0',                       ...
                                           'Units','normalized',               ...
                                           'Position',[0.45 0.25 0.15 0.3],       ...
                                           'Callback',{@edit_hieghtCallback,h}, ...
                                           'Tag','Height');
                                       
                                       
    view_button        = uicontrol('style','pushbutton','Parent',panel_levels, ...
                                                        'String','Building 3D',      ...
                                                        'Units','normalized',  ...
                                                        'Position',[0.7 0.2 0.25 0.6], ...
                                                        'Callback',{@btn_viewCallback,h}, ...
                                                        'Tag','view');
                                                    
end

