function CT01_pc_levels(h,panel_levels)
%% Panel Title: Levels


    w = 0.25; 

    listbox_levels     = uicontrol('style','listbox',    'Parent',panel_levels,    ...
                                                         'String',[],             ...
                                                         'Units','normalized',     ... 
                                                         'Enable','off',            ...
                                                         'Position',[0.05 0.1 w 0.8], ...
                                                         'Callback',{@listbox_planimetryCallback,h}, ...
                                                         'Tag','listbox');
    
    wb = 0.13;
    hb = 0.25;
    x  = 0.35;
    
    button_add_level   = uicontrol('style','pushbutton','Parent',panel_levels, ...
                                                        'FontSize',15,         ...
                                                        'String','+',          ...
                                                        'Units','normalized',  ...
                                                         'Enable','off',            ...
                                                        'Position',[x 0.5 wb hb], ...
                                                        'Callback',{@btn_addCallback,h}, ...
                                                        'Tag','add');
                                                    
    button_minus_level = uicontrol('style','pushbutton','Parent',panel_levels, ...
                                                        'FontSize',15,         ...
                                                        'String','-',          ...
                                                        'Units','normalized',  ...
                                                         'Enable','off',            ...
                                                        'Position',[x 0.18 wb hb], ...
                                                        'Callback',{@btn_minusCallback,h}, ...
                                                        'Tag','minus');

                                                    
    text_hieght = uicontrol('style','text','Parent',panel_levels, ...
                                           'String','Height',     ...
                                           'Units','normalized',  ...
                                           'Position',[0.6 0.55 0.25 0.3]);
                                       
    edit_hieght = uicontrol('style','edit','Parent',panel_levels,              ...
                                           'String','0',                       ...
                                           'Units','normalized',               ...
                                            'Enable','off',            ...
                                           'Position',[0.65 0.25 0.15 0.3],       ...
                                           'Callback',{@edit_hieghtCallback,h}, ...
                                           'Tag','Height');
                                       
                                       
end

