function CT01_pc_buildings(h,panel_levels)
%% Panel Title: Levels
    
    w = 0.25; 

    listbox_buildings     = uicontrol('style','listbox',    'Parent',panel_levels,    ...
                                                         'String',[],             ...
                                                         'Units','normalized',     ... 
                                                          'Enable','off',            ...
                                                         'Position',[0.05 0.1 w 0.8], ...
                                                         'Callback',{@listbox_planimetryCallbackBuildings,h}, ...
                                                         'Tag','listbox');
    
    wb = 0.13;
    hb = 0.25;
    x  = 0.35;
    
    button_add_level   = uicontrol('style','pushbutton','Parent',panel_levels, ...
                                                        'FontSize',15,         ...
                                                        'String','+',          ...
                                                        'Units','normalized',  ...
                                                        'Position',[x 0.5 wb hb], ...
                                                        'Callback',{@btn_addCallbackBuildings,h}, ...
                                                        'Tag','add');
                                                    
    button_minus_level = uicontrol('style','pushbutton','Parent',panel_levels, ...
                                                        'FontSize',15,         ...
                                                        'String','-',          ...
                                                        'Units','normalized',  ...
                                                         'Enable','off',            ...
                                                        'Position',[x 0.2 wb hb], ...
                                                        'Callback',{@btn_minusCallbackBuildings,h}, ...
                                                        'Tag','minus');

                                                    
    wb = 0.35;
    view_button        = uicontrol('style','pushbutton','Parent',panel_levels, ...
                                                        'String','Building 3D',      ...
                                                        'Units','normalized',  ...
                                                         'Enable','off',            ...
                                                        'Position',[0.55 0.2 wb 0.6], ...
                                                        'Callback',{@btn_viewCallback,h}, ...
                                                        'Tag','view');
                                                    
end

