function CT03_panel_control(h,panel_control)
%CT02_PANEL_CONTROL Summary of this function goes here
%   Detailed explanation goes here
    %% Tabs 
    tabgp = uitabgroup(panel_control,                       ...
                       'Units','normalize',                 ...
                       'Position',[0.00 0.00 0.4 1],       ...
                       'Tag','Tab');          
                   
                   
   color = [ 0 0 0.75];
                
   %% Beacon Based               
   tab_beacon_based_sgn   = uitab(tabgp,'Title','Beacon Based','Tag','Beacon Based');
   tab_beacon_based_sgn.ForegroundColor = color;

           popBBS = uicontrol('style','popupmenu',              ...
                              'String',{'RSS','ToF','AoA'},     ...
                              'Units','normalized',             ...
                              'Position',[0.05 0.4 0.3 0.2],    ...
                              'Parent',tab_beacon_based_sgn,    ...
                              'Tag','popupmenu');
                     
           panel_filter = uipanel(tab_beacon_based_sgn,'Title','Filter Aps','Units','normalized','Position',[0.4 0.0 0.6 1.0]);
                    
                   text_max_att = uicontrol('style','text',             ...
                                            'Parent',panel_filter,      ...
                                            'String','Max dB',          ...
                                            'Units','normalized',       ...
                                            'Position',[0.0825 0.3 0.3 0.4]);

                   edit_max_att = uicontrol('style','edit',               ...
                                            'Parent',panel_filter,        ...
                                            'String',' ',                 ...
                                            'Units','normalized',         ...
                                            'Position',[0.4 0.325 0.15 0.3], ...
                                            'Tag','Max dB');               

                   btn_filter  = uicontrol('style','pushbutton',          ...
                                           'Parent',panel_filter,         ...
                                           'Units','normalized',          ...
                                           'String','Filter!',            ...
                                           'Position',[0.7 0.325 0.2 0.3]);
    %% Beacon Free
   tab_beacon_free_sgn    = uitab(tabgp,'Title','Beacon Free','Tag','Beacon Free');
   tab_beacon_free_sgn.ForegroundColor  = color;

           popBBS = uicontrol('style','popupmenu',  ...
                              'String',{'Baro','Gyro','Acel','Magne'},   ...
                              'Units','normalized', ...
                              'Position',[0.1 0.3 0.8 0.2], ...
                              'Parent',tab_beacon_free_sgn, ...
                              'Tag','popupmenu');
   


   
    %%  Engine Functions 
    uipanel(panel_control,'Units','normalize',                ...
                       'Position',[0.4 0.02 0.475 0.96],      ...
                       'Title','Engine functions',            ...
                       'Tag','SignalType'); 
           
    %% Generation Button       
    generation_panel = uipanel(panel_control,'Units','normalize',                ...
                       'Position',[0.875 0.02 0.125 0.96],      ...
                       'Title','Generation',            ...
                       'Tag','SignalType');   
                   
                   uicontrol('Style','pushbutton',                  ...
                             'Parent',generation_panel,             ...
                             'String','Generate',                   ...
                             'FontSize',12,                         ...
                             'FontName','Comic Sans MS',            ...
                             'Units','normalized',                  ...
                             'Position',[0.1 0.325 0.8 0.35],         ...
                             'Callback',{@generationSignalCalback,h})

            
end


