function CT04_panel_control(h,panel_control)
%CT04_PANEL_CONTROL Summary of this function goes here
%   Detailed explanation goes here

    %% Engine funtions 
 panel_algorithms = uipanel(panel_control,'Units','normalized','Position',[0.01 0.05 0.87 0.95],'Title','Algorithms','Tag','Algorithms');

    uicontrol('style','text','Parent',panel_algorithms,'Units','normalized','Position',[0.05 0.25 0.25 0.6],'String','Tracking-Algorithms:')
    uicontrol('style','listbox','Parent',panel_algorithms,'Units','normalized','Position',[0.3 0.1 0.32 0.8],'Tag','listbox','Tag','listbox','Callback',{@openfile_listbox,h})
    %
    h.javacomponets.processing_layer.addFcnBeaconBased    = add_btn('Parent',panel_algorithms,    ...
                                                            'Position',[0.65 0.6 0.04 0.3],           ...
                                                            'Callback',{@addFcnlistbox,h},          ...
                                                            'Tag','addAlgorithms');
    h.javacomponets.processing_layer.minusFcnBeaconBased    = minus_btn('Parent',panel_algorithms,  ...
                                                            'Position',[0.65 0.2 0.04 0.3],           ...
                                                            'Callback',{@minusFcnlistbox,h},        ...
                                                            'Tag','minusAlgorithms');

    
%   %% Initial State
%         panel_other = uipanel(panel_control,'Units','normalized','Position',[0.65 0.05 0.25 0.95],'Title','Initial State','Tag','Initial State');
%         
%                 uicontrol('style','checkbox','Parent',panel_other,'String','By default','Units','normalized','Position',[0.1 0.7 0.8 0.3],'Tag','By default','Callback',{@checkbox_bydefault,h})
%                 
%                 if ismac
%                     FontSize = 14;
%                 end
%                 if ispc
%                     FontSize = 12;
%                 end
%                 uicontrol('style','text','Parent',panel_other,'String','[  x  ,   y  ,   h  ,  vx  , vy  ]','Units','normalized','Position',[0.0 0.475 1 0.275],'FontSize',FontSize)
%                 uicontrol('style','edit','Parent',panel_other,'String','[0.00 , 0.00 , 0.00 , 0.00 , 0.00]','Units','normalized','Position',[0.05 0.1 0.9 0.3],'Tag','InitialState')

  %% Compute!
        uicontrol('Style','pushbutton',             ...
                  'Parent',panel_control,           ...
                  'Units','normalized',             ...
                  'Position',[0.9 0.5 0.08 0.3],   ...
                  'String','Compute!',              ...
                  'Callback',{@btnComputeCallback,h});
              
    %% Animation
        uicontrol('Style','pushbutton',             ...
                  'Parent',panel_control,           ...
                  'Units','normalized',             ...
                  'Position',[0.9 0.2 0.08 0.3],   ...
                  'String','Animation',             ...
                  'Tag','Animation',                ...
                  'Callback',{@animationProcessingCallback,h});            
end

