function CT03_panel_signals(h,panel_signals)
%CT02_PANEL_SUPERTRAJS Summary of this function goes here
%   Detailed explanation goes here
    


    listbox_signals  = uicontrol('style','listbox',     'Parent',panel_signals,        ...
                                                        'FontName','Comic Sans MS',    ...
                                                         'String','' ,                 ...
                                                         'Units','normalized',         ... 
                                                         'Position',[0.1 0.1 0.75 0.8], ...
                                                         'Callback',{@listbox_signalCallback,h}, ...
                                                          'FontSize',12, ...
                                                         'FontWeight','bold', ...
                                                         'Tag','listbox');

    h.javacomponets.signal_layer.add_supertraj_btn    = add_btn('Parent',panel_signals, ...
                                                            'Position',[0.875 0.6 0.1 0.2], ...
                                                            'Callback',{@add_signalCallback,h}, ...
                                                            'Tag','add');
    
    
    h.javacomponets.signal_layer.minus_supertraj_btn  = minus_btn('Parent',panel_signals, ...
                                                            'Position',[0.875 0.3 0.1 0.2], ...
                                                            'Callback',{@minus_signalCallback,h}, ...
                                                         'Tag','minus');
                                                    
end

