function CT04_panel_straj_estimation(h,panel_straj_estimation)
%CT02_PANEL_SUPERTRAJS Summary of this function goes here
%   Detailed explanation goes here
    

    uicontrol('style','listbox',     'Parent',panel_straj_estimation,        ...
                                                         'String','' ,                 ...
                                                         'Units','normalized',         ... 
                                                          'Position',[0.1 0.1 0.6 0.8], ...
                                                         'Callback',{@listbox_processingCallback,h}, ...
                                                         'Tag','listbox');

%     button_add_level   = uicontrol('style','pushbutton','Parent',panel_straj_estimation, ...
%                                                         'FontSize',15,         ...
%                                                         'String','+',          ...
%                                                         'Units','normalized',  ...
%                                                         'Position',[0.75 0.85 0.15 0.05], ...
%                                                         'Callback',{@add_processingCallback,h}, ...
%                                                         'Tag','add');
% 
%     button_minus_level = uicontrol('style','pushbutton','Parent',panel_straj_estimation, ...
%                                                         'FontSize',15,         ...
%                                                         'String','-',          ...
%                                                         'Units','normalized',  ...
%                                                         'Position',[0.75 0.775 0.15 0.05], ...
%                                                         'Callback',{@minus_processingCallback,h}, ...
%                                                         'Tag','minus');


    h.javacomponets.signal_layer.add_supertraj_btn    = add_btn('Parent',panel_straj_estimation, ...
                                                            'Position',[0.75 0.825 0.15 0.1], ...
                                                            'Callback',{@add_processingCallback,h}, ...
                                                            'Tag','add');
    
    
    h.javacomponets.signal_layer.minus_supertraj_btn  = minus_btn('Parent',panel_straj_estimation, ...
                                                            'Position',[0.75 0.725 0.15 0.1], ...
                                                            'Callback',{@minus_processingCallback,h}, ...
                                                         'Tag','minus');
end

